# Generated by Django 5.2.5 on 2025-08-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_autor_nome_alter_categoria_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(blank=True),
        ),
    ]
